dist: trusty
language: python
python:
    - "3.5"

install:
  - "git clone https://github.com/mjs/imapclient.git"
  - "cd imapclient; python setup.py install"
script: "find"

notifications:
  email:
    recipients:
      - imapclient-notifications@freshfoo.com
    on_success: never
    on_failure: never
