dist: trusty
language: python
before_install:
- openssl aes-256-cbc -K $encrypted_c760f38e794c_key -iv $encrypted_c760f38e794c_iv -in ini.tar.enc -out ini.tar -d
- tar xvf ini.tar
python:
- '2.7'
- '3.5'
env:
- SVC=gmail
- SVC=fastmail
install:
- git clone https://github.com/mjs/imapclient.git
- cd imapclient
- git checkout 1.x
- python setup.py install
script:
- python livetest.py ../$SVC.ini
notifications:
  email:
    recipients:
    - imapclient-notifications@freshfoo.com
    on_success: never
    on_failure: never
