dist: trusty
language: python
python:
- '3.5'
before_install:
- openssl aes-256-cbc -K $encrypted_c760f38e794c_key -iv $encrypted_c760f38e794c_iv -in fastmail.ini.enc -out fastmail.ini -d
install:
- git clone https://github.com/mjs/imapclient.git
- cd imapclient
- git checkout 1.x
- python setup.py install
script: python livetest.py ../fastmail.ini
notifications:
  email:
    recipients:
    - imapclient-notifications@freshfoo.com
    on_success: never
    on_failure: never
